[package]
name = "tomfoolery"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.42", features = ["serde"] }
csv = "1.4.0"
rusqlite = { version = "0.37.0", features = ["chrono"] }
serde = { version = "1.0.228", features = ["derive"] }
